//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xknote
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_info
    {
        public long id { get; set; }
        public long uid { get; set; }
        public string blog_system { get; set; }
        public string blog_url { get; set; }
        public string blog_username { get; set; }
        public string blog_password { get; set; }
        public string blog_token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
