//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xknote
{
    using System;
    using System.Collections.Generic;
    
    public partial class git_info
    {
        public long id { get; set; }
        public Nullable<long> uid { get; set; }
        public string git_name { get; set; }
        public string git_email { get; set; }
        public string git_password { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
