//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xknote
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_config
    {
        public long id { get; set; }
        public Nullable<long> uid { get; set; }
        public string tinymce_setting { get; set; }
        public string ace_setting { get; set; }
        public string xk_setting { get; set; }
    }
}
