//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xknote
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public long id { get; set; }
        public string username { get; set; }
        public string nickname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> email_verif { get; set; }
        public string password { get; set; }
        public string remember_to { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
